In [2]:
import numpy as np

## Initializing Numpy Arrays

In [10]:
zeroes = np.zeros((3,3))
print(zeroes)

ones = np.ones_like(zeroes)
print(ones)

identity = np.identity(3)
print(identity)

lst = [[1,2,3],[4,5,6]]
np_arr = np.array(lst)
print(np_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 2 3]
 [4 5 6]]


## Checking commonly used metadata of arrays

In [11]:
zeroes = np.zeros((3,3))
print(zeroes)
print("Data Type:", zeroes.dtype)
print("Shape:", zeroes.shape)
print("Dimensions:", zeroes.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Data Type: float64
Shape: (3, 3)
Dimensions: 2


## Numpy Arithmetic

In [16]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print(arr + arr)
print(arr * 2)

arr_2 = np.array([[1., 2., 3.], [3., 2., 1.]])
print(arr > arr_2)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[False False False]
 [ True  True  True]]


## Indexing and Slicing

In [28]:
# Single Dimension

arr = np.array([0., 1., 2., 3., 4., 5., 6.])
print(arr[0])
print(arr[4:])
print(arr[:3])
print(arr[3:6])

0.0
[4. 5. 6.]
[0. 1. 2.]
[3. 4. 5.]


In [34]:
# Multi Dimension

arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr[0])
print(arr[0,0])
print(arr[1,0])
print(arr[:1, :1])

[1. 2. 3.]
1.0
4.0
[[1.]]


## Boolean Indexing

In [39]:
arr = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

print(arr[arr == 'Joe'])
print(arr[arr != 'Joe'])

cond = (arr != 'Bob') & (arr != 'Will')

print(arr[cond])
print(arr[~cond])

['Joe' 'Joe' 'Joe']
['Bob' 'Will' 'Bob' 'Will']
['Joe' 'Joe' 'Joe']
['Bob' 'Will' 'Bob' 'Will']


## Fancy Indexing


In [57]:
arr = np.empty((3, 3))

for i in range(3):
    arr[i] = i

print(arr[[1,2]])
print(arr[[0,2]])

arr = np.arange(32).reshape((8, 4))
print(arr)
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]])

[[1. 1. 1.]
 [2. 2. 2.]]
[[0. 0. 0.]
 [2. 2. 2.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[ 4 23 29 10]
