In [1]:
import numpy as np

In [2]:
# Create a sample array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [3]:
# Mean of array
mean = np.mean(arr)
print("Mean of array:", mean)

Mean of array: 5.0


In [4]:
# Median of array
median = np.median(arr)
print("Median of array:", median)

Median of array: 5.0


In [8]:
# Rank of array
rank = np.linalg.matrix_rank(arr)
print("Rank of array:", rank)

Rank of array: 2


In [9]:
# Quantiles of array
quantiles = np.quantile(arr, [0.25, 0.5, 0.75])
print("Quantiles of array:", quantiles)

Quantiles of array: [3. 5. 7.]


In [11]:
# Probability distribution
normal_dist = np.random.normal(0, 1, 1000) # generate 1000 samples from a normal distribution with mean 0 and standard deviation 1
print("Normal distribution:", normal_dist)


Normal distribution: [ 7.11521798e-03  1.19959030e-02  1.98201957e+00  1.68415627e+00
 -1.20101908e+00 -1.21098804e-01 -1.75628495e+00  4.48144039e-01
  3.68734891e-01  1.44684375e+00  8.04972236e-01  8.58077425e-01
  2.73373907e-01 -1.31058790e+00  3.30560942e-01 -1.56850211e+00
  8.10359154e-01 -4.67132240e-01 -1.00088452e+00  6.59857200e-01
 -1.70417219e+00  1.23767358e+00 -3.53195537e-01  1.03216131e+00
 -9.02830766e-01  1.23573524e+00 -1.22896432e+00  6.31641451e-01
 -1.32076949e+00 -6.17076927e-01 -1.17064308e+00 -8.87217017e-01
  6.41256947e-01  5.14242500e-01  5.59731333e-01  6.85894077e-01
  5.67815767e-01 -1.06401603e+00  1.93860743e-01 -6.49985960e-01
 -1.01795142e+00 -5.47239638e-01  5.90470773e-01  1.99131956e-01
  8.59145765e-01 -1.67639383e+00  1.13236507e+00  7.55333879e-02
 -1.07130178e+00  1.20248683e+00  2.40318500e-01 -2.74781246e+00
 -7.20591440e-01  9.26705388e-01  4.70579914e-01  1.83217252e-01
 -6.84490578e-01 -1.18969747e+00 -1.62227983e+00  5.55302723e-01
 -4.

In [12]:
# Correlation between two arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
corr = np.corrcoef(a, b)
print("Correlation between a and b:", corr)

Correlation between a and b: [[1. 1.]
 [1. 1.]]


In [16]:
arr = np.array([[3, 2, 3], [4, 5, 6], [7, 8, 9]])

# Transpose of array
transpose = np.transpose(arr)
print("Transpose of array:\n", transpose)

Transpose of array:
 [[3 4 7]
 [2 5 8]
 [3 6 9]]


In [17]:
# Determinant of array
det = np.linalg.det(arr)
print("Determinant of array:", det)

Determinant of array: -6.0000000000000036


In [18]:
# Inverse of array
inv = np.linalg.inv(arr)
print("Inverse of array:\n", inv)

Inverse of array:
 [[ 0.5        -1.          0.5       ]
 [-1.         -1.          1.        ]
 [ 0.5         1.66666667 -1.16666667]]


In [19]:
# Eigenvalues and eigenvectors of array
eigvals, eigvecs = np.linalg.eig(arr)
print("Eigenvalues of array:", eigvals)
print("Eigenvectors of array:\n", eigvecs)

Eigenvalues of array: [16.36660027  1.         -0.36660027]
Eigenvectors of array:
 [[-0.2603943  -0.82956136 -0.30110589]
 [-0.5207886   0.51847585 -0.60221177]
 [-0.8130031   0.20739034  0.73937557]]


In [20]:
# Dot product of two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print("Dot product of a and b:", dot_product)

Dot product of a and b: 32


In [21]:
# Cross product of two arrays
c = np.array([1, 2, 3])
d = np.array([4, 5, 6])
cross_product = np.cross(c, d)
print("Cross product of c and d:", cross_product)

Cross product of c and d: [-3  6 -3]


In [22]:
# Covariance between two arrays
e = np.array([1, 2, 3, 4, 5])
f = np.array([6, 7, 8, 9, 10])
cov = np.cov(e, f)
print("Covariance between e and f:", cov)

Covariance between e and f: [[2.5 2.5]
 [2.5 2.5]]
