In [1]:
import numpy as np

In [3]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = 5

c = a + b

print(c) 


[6 7 8 9]


In [4]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])

c = a * b

print(c) 


[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]


In [8]:
import numpy as np

a = np.array([3, 4, 5])
b = np.array([1, 2, 3, 4, 5])

c = a * b[:, np.newaxis, np.newaxis]

print(c)
print(c.shape) 

[[[ 3  4  5]]

 [[ 6  8 10]]

 [[ 9 12 15]]

 [[12 16 20]]

 [[15 20 25]]]
(5, 1, 3)


In [9]:
import numpy as np

a = np.ones((3, 4))
b = np.array([1, 2, 3])

c = a + b[:, np.newaxis]

print(c) 


[[2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


In [10]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = a > 2

c = a[b]

print(c)


[3 4 5]


In [12]:
import numpy as np

a = np.array([1, 2, 3], dtype=np.float32)
b = 2

c = a * b

print(c) 


[2. 4. 6.]


In [14]:
import numpy as np

a = np.array([1, 2, 3])
b = 2 + 3j

c = a * b

print(c) 


[2.+3.j 4.+6.j 6.+9.j]


In [16]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = a[:, :2]

c = b * 2

print(c) 


[[ 2  4]
 [ 8 10]]
